const emocionesExteriores = [
  { valor: 1, label: "INSPIRADO", tipo: "Felicidad" },
  { valor: 1, label: "ABIERTO", tipo: "Felicidad" },
  { valor: 1, label: "BROMISTA", tipo: "Felicidad" },
  { valor: 1, label: "SENSIBLE", tipo: "Felicidad" },
  { valor: 1, label: "ESPERANZADO", tipo: "Felicidad" },
  { valor: 1, label: "CARIÑOSO", tipo: "Felicidad" },
  { valor: 1, label: "PROVOCATIVO", tipo: "Felicidad" },
  { valor: 1, label: "VALIENTE", tipo: "Felicidad" },
  { valor: 1, label: "SATISFECHO", tipo: "Felicidad" },
  { valor: 1, label: "RESPETADO", tipo: "Felicidad" },
  { valor: 1, label: "SEGURO", tipo: "Felicidad" },
  { valor: 1, label: "IMPORTANTE", tipo: "Felicidad" },
  { valor: 1, label: "IMPORTANTE", tipo: "Felicidad" },
  { valor: 1, label: "CURIOSO", tipo: "Felicidad" },
  { valor: 1, label: "ENTRETENIDO", tipo: "Felicidad" },
  { valor: 1, label: "EUFÓRICO", tipo: "Felicidad" },
  { valor: 1, label: "LIBERADO", tipo: "Felicidad" },
  { valor: 1, label: "APENADO", tipo: "Ira" },
  { valor: 1, label: "DESVASTADO", tipo: "Ira" },
  { valor: 1, label: "ATACADO", tipo: "Ira" },
  { valor: 1, label: "CELOSO", tipo: "Ira" },
  { valor: 1, label: "RESENTIDO", tipo: "Ira" },
  { valor: 1, label: "ULTRAJADO", tipo: "Ira" },
  { valor: 1, label: "FURIOSO", tipo: "Ira" },
  { valor: 1, label: "RABIOSO", tipo: "Ira" },
  { valor: 1, label: "PROVOCADOR", tipo: "Ira" },
  { valor: 1, label: "HOSTIL", tipo: "Ira" },
  { valor: 1, label: "ENFURECIDO", tipo: "Ira" },
  { valor: 1, label: "IRRITADO", tipo: "Ira" },
  { valor: 1, label: "INTROVERTIDO", tipo: "Ira" },
  { valor: 1, label: "DESCONFIADO", tipo: "Ira" },
  { valor: 1, label: "ESCÉPTICO", tipo: "Ira" },
  { valor: 1, label: "SARCÁSTICO", tipo: "Ira" },
  { valor: 1, label: "ARREPENTIDO", tipo: "Tristeza" },
  { valor: 1, label: "AVERGONZADO", tipo: "Tristeza" },
  { valor: 1, label: "IGNORADO", tipo: "Tristeza" },
  { valor: 1, label: "VICTIMIZADO", tipo: "Tristeza" },
  { valor: 1, label: "DESVALIDO", tipo: "Tristeza" },
  { valor: 1, label: "VULNERABLE", tipo: "Tristeza" },
  { valor: 1, label: "MELANCÓLICO", tipo: "Tristeza" },
  { valor: 1, label: "VACÍO", tipo: "Tristeza" },
  { valor: 1, label: "DESAMPARADO", tipo: "Tristeza" },
  { valor: 1, label: "AISLADO", tipo: "Tristeza" },
  { valor: 1, label: "APÁTICO", tipo: "Tristeza" },
  { valor: 1, label: "INDIFERENTE", tipo: "Tristeza" },
  { valor: 1, label: "ATERRADO", tipo: "Miedo" },
  { valor: 1, label: "ESPANTADO", tipo: "Miedo" },
  { valor: 1, label: "AGOBIADO", tipo: "Miedo" },
  { valor: 1, label: "PREOCUPADO", tipo: "Miedo" },
  { valor: 1, label: "INSUFICIENTE", tipo: "Miedo" },
  { valor: 1, label: "INFERIOR", tipo: "Miedo" },
  { valor: 1, label: "INÚTIL", tipo: "Miedo" },
  { valor: 1, label: "INSIGNIFICANTE", tipo: "Miedo" },
  { valor: 1, label: "MARGINADO", tipo: "Miedo" },
  { valor: 1, label: "ALIENADO", tipo: "Miedo" },
  { valor: 1, label: "IRRESPETADO", tipo: "Miedo" },
  { valor: 1, label: "RIDICULIZADO", tipo: "Miedo" },
  { valor: 1, label: "ENÉRGETICO", tipo: "Sorpresa" },
  { valor: 1, label: "ENTUSIASTA", tipo: "Sorpresa" },
  { valor: 1, label: "IMPRESIONADO", tipo: "Sorpresa" },
  { valor: 1, label: "ESTUPEFACTO", tipo: "Sorpresa" },
  { valor: 1, label: "PERPLEJO", tipo: "Sorpresa" },
  { valor: 1, label: "DESILUSIONADO", tipo: "Sorpresa" },
  { valor: 1, label: "ABATIDO", tipo: "Sorpresa" },
  { valor: 1, label: "CONMOCIONADO", tipo: "Sorpresa" },
  { valor: 1, label: "MORALISTA", tipo: "Asco" },
  { valor: 1, label: "REACIO", tipo: "Asco" },
  { valor: 1, label: "REPUGNANTE", tipo: "Asco" },
  { valor: 1, label: "REVOLTOSO", tipo: "Asco" },
  { valor: 1, label: "ASCO", tipo: "Asco" },
  { valor: 1, label: "ODIOSO", tipo: "Asco" },
  { valor: 1, label: "AVERSIÓN", tipo: "Asco" },
  { valor: 1, label: "VACILANTE", tipo: "Asco" },
];
const emocionesInteriores = [
  { valor: 1, label: "OPTIMISTA", tipo: "Felicidad" },
  { valor: 1, label: "ÍNTIMO", tipo: "Felicidad" },
  { valor: 1, label: "PACÍFICO", tipo: "Felicidad" },
  { valor: 1, label: "PODEROSO", tipo: "Felicidad" },
  { valor: 1, label: "ACEPTADO", tipo: "Felicidad" },
  { valor: 1, label: "ORGULLOSO", tipo: "Felicidad" },
  { valor: 1, label: "ASOMBRADO", tipo: "Felicidad" },
  { valor: 1, label: "INTERESADO", tipo: "Felicidad" },
  { valor: 1, label: "ALEGRE", tipo: "Felicidad" },
  { valor: 1, label: "HERIDO", tipo: "Ira" },
  { valor: 1, label: "AMENAZADO", tipo: "Ira" },
  { valor: 1, label: "LLENO DE ODIO", tipo: "Ira" },
  { valor: 1, label: "LOCO", tipo: "Ira" },
  { valor: 1, label: "AGRESIVO", tipo: "Ira" },
  { valor: 1, label: "FRUSTRADO", tipo: "Ira" },
  { valor: 1, label: "DISTANTE", tipo: "Ira" },
  { valor: 1, label: "CRÍTICO", tipo: "Ira" },
  { valor: 1, label: "CULPABLE", tipo: "Tristeza" },
  { valor: 1, label: "ABANDONADO", tipo: "Tristeza" },
  { valor: 1, label: "DESESPERADO", tipo: "Tristeza" },
  { valor: 1, label: "DEPRIMIDO", tipo: "Tristeza" },
  { valor: 1, label: "SOLO", tipo: "Tristeza" },
  { valor: 1, label: "ABURRIDO", tipo: "Tristeza" },
  { valor: 1, label: "ASUSTADO", tipo: "Miedo" },
  { valor: 1, label: "ANSIOSO", tipo: "Miedo" },
  { valor: 1, label: "INSEGURO", tipo: "Miedo" },
  { valor: 1, label: "SUMISO", tipo: "Miedo" },
  { valor: 1, label: "RECHAZADO", tipo: "Miedo" },
  { valor: 1, label: "HUMILLADO", tipo: "Miedo" },
  { valor: 1, label: "ENTUSIASMADO", tipo: "Sorpresa" },
  { valor: 1, label: "ASOMBRADO", tipo: "Sorpresa" },
  { valor: 1, label: "CONFUNDIDO", tipo: "Sorpresa" },
  { valor: 1, label: "SORPRENDIDO", tipo: "Sorpresa" },
  { valor: 1, label: "DISCONFORME", tipo: "Asco" },
  { valor: 1, label: "DECEPCIONADO", tipo: "Asco" },
  { valor: 1, label: "HORRIBLE", tipo: "Asco" },
  { valor: 1, label: "ABSTINENCIA", tipo: "Asco" },
];
const emocionesCentrales = [
  { label: "TRISTEZA", tipo: "Tristeza", valor: 2.3 },

  { label: "FELICIDAD", tipo: "Felicidad", valor: 3.2 },

  { label: "SORPRESA", tipo: "Sorpresa", valor: 1.5 },

  { label: "MIEDO", tipo: "Miedo", valor: 2 },

  { label: "IRA", tipo: "Ira", valor: 3 },

  { label: "ASCO", tipo: "Asco", valor: 1.5 },
];
export { emocionesCentrales, emocionesExteriores, emocionesInteriores };

// 8, 25, 33, 45, 61, 71, 81, 90, 94, 100, 108, 113, 116, 117, 118, 119;
